# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9321b66a4284979fcb8f84c5d115e7994da7223390df5e3c4a049e6921468172881def9d6b8cfb9f53396bdd41608577badf570a2693d82136e84ff48d4b3b8

test:
  secret_key_base: 821d6a9d9ccf64e760c6c50454c1b8cc8780d934daa4d7956666e3f7d33a4220b32c394948ada27a80ce399222dffaff24a910e6dd67c1faeed0df462cb88337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
